name: update-docs-repo
on:
  push:
    branches:    
      - dev
    paths:
      - docker/docker-compose.yml
  workflow_dispatch:
    

jobs:
  copy-docker-compose-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: dev

    - name: Pushes docker-compose
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_TOKEN }}
      with:
        source_file: 'docker/docker-compose.yml'
        destination_repo: 'Bubka/2FAuth-Docs'
        destination_folder: 'docs/static'
        user_email: '858858+Bubka@users.noreply.github.com'
        user_name: 'Bubka'
        commit_message: '[Auto] Update docker-compose file'
